# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='python_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=255, verbose_name='関数名')),
                ('program_name', models.CharField(max_length=255, verbose_name='プログラム名')),
                ('tag', models.CharField(blank=True, max_length=255, verbose_name='タグ名')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='著者名')),
                ('Github', models.CharField(blank=True, max_length=255, verbose_name='Github')),
            ],
        ),
    ]
