# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_python_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='python_book',
        ),
    ]
