# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_delete_python_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='python_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(max_length=255, verbose_name='関数名')),
                ('program_name', models.CharField(max_length=255, verbose_name='プログラム名')),
                ('tag', models.CharField(blank=True, max_length=255, verbose_name='タグ名')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='著者名')),
                ('Github', models.CharField(blank=True, max_length=255, verbose_name='Github')),
            ],
        ),
        migrations.CreateModel(
            name='python_Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.python_Book', verbose_name='関数名')),
            ],
        ),
    ]
